version: '1.0'

services:
  moodle:
    image: moodlehq/moodle-php-apache:8.2
    container_name: moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      - MOODLE_DBTYPE=mysqli
      - MOODLE_DBHOST=db
      - MOODLE_DBNAME=moodle
      - MOODLE_DBUSER=moodle
      - MOODLE_DBPASS=moodle
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
  db_data:
