version: '3.8'

services:
  moodle:
    image: moodlehq/moodle-php-apache:8.2
    container_name: moodle
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      - MOODLE_DBTYPE=mysqli
      - MOODLE_DBHOST=db
      - MOODLE_DBNAME=moodle
      - MOODLE_DBUSER=moodle
      - MOODLE_DBPASS=moodle
    volumes:
      - ./moodledata:/bitnami/moodle
      - ./moodle:/var/www/html

  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
  db_data:
